name: Run News Parser
on:
  schedule:
    - cron: '0 */6 * * *'  # Каждый 6 часов
 # workflow_dispatch:  # Добавленная строка..
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests beautifulsoup4 python-telegram-bot
      - run: python absl_rating_news_parser.py
